CREATE OR REPLACE PROCEDURE PR_OBT_EMPLEADO (P_EMPLOYEE_ID IN NUMBER, P_SALARY OUT NUMBER, P_JOB_ID OUT VARCHAR2, P_ID OUT NUMBER, P_ERROR OUT VARCHAR2)
AS
BEGIN
    SELECT SALARY, JOB_ID INTO P_SALARY, P_JOB_ID FROM EMPLOYEES WHERE EMPLOYEE_ID=P_EMPLOYEE_ID;
    P_ID := 1;
EXCEPTION
    WHEN OTHERS THEN
        P_ID := -1;
        P_ERROR := SQLERRM;
        
END PR_OBT_EMPLEADO;
/
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID=100;
/
SET SERVEROUTPUT ON;
DECLARE
V_ERROR VARCHAR2(100);
V_ID NUMBER;
V_SALARY NUMBER;
V_JOB_ID VARCHAR2(50);
BEGIN
    PR_OBT_EMPLEADO(100, V_SALARY, V_JOB_ID, V_ID, V_ERROR);
    DBMS_OUTPUT.PUT_LINE('SALARY: ' || V_SALARY || ' - JOB ID: ' || V_JOB_ID);
    DBMS_OUTPUT.PUT_LINE('P_ID: ' || V_ID || ' - ' || V_ERROR);
END;
