create or replace PROCEDURE PR_INSERTAR_TRABAJO (
    P_JOB_ID VARCHAR2,
    P_JOB_TITLE	VARCHAR2,
    P_ERROR OUT VARCHAR2,
    P_ID OUT NUMBER
    )
AS
BEGIN
    INSERT INTO JOBS(JOB_ID, JOB_TITLE) VALUES (P_JOB_ID, P_JOB_TITLE);
    P_ID := 1;
EXCEPTION
    WHEN OTHERS THEN
        P_ID := -1;
        P_ERROR := SQLERRM;
        DBMS_OUTPUT.PUT_LINE('ERROR : JOB_ID ' || P_JOB_ID);
        
END PR_INSERTAR_TRABAJO;
/
SET SERVEROUTPUT ON;
DECLARE
V_ERROR VARCHAR2(100);
V_ID NUMBER;
BEGIN
--ERROR YA EXISTE JOB_ID
PR_INSERTAR_TRABAJO('AD_PRES','President', V_ERROR, V_ID);
DBMS_OUTPUT.PUT_LINE(V_ERROR || 'P_ID: ' || V_ID);
--INSERCION DE IT_DBA
PR_INSERTAR_TRABAJO('IT_DBA','Database Administrator', V_ERROR, V_ID);
DBMS_OUTPUT.PUT_LINE(V_ERROR || 'P_ID: ' || V_ID);
END;
/
SELECT JOB_ID, JOB_TITLE FROM JOBS WHERE JOB_ID='IT_DBA';