CREATE OR REPLACE PROCEDURE PR_ACTUALIZAR_SALARIOS 
(
    P_JOB_ID VARCHAR2,
    P_NEW_SALARY NUMBER,
    P_ID OUT NUMBER,
    P_ERROR OUT VARCHAR2
)
AS
E_SALARY_OUT_OF_BOUNDS EXCEPTION;
V_MAX_SALARY NUMBER;
V_MIN_SALARY NUMBER;
V_BOUND_TRESPASSED BOOLEAN;
BEGIN

    SELECT MIN_SALARY, MAX_SALARY INTO V_MIN_SALARY, V_MAX_SALARY FROM JOBS WHERE JOB_ID=P_JOB_ID;
    IF V_MIN_SALARY IS NOT NULL AND P_NEW_SALARY<V_MIN_SALARY THEN
        V_BOUND_TRESPASSED := FALSE;
        RAISE E_SALARY_OUT_OF_BOUNDS;
    END IF;
    IF V_MAX_SALARY IS NOT NULL AND P_NEW_SALARY>V_MAX_SALARY THEN
        V_BOUND_TRESPASSED := TRUE;
        RAISE E_SALARY_OUT_OF_BOUNDS;
    END IF;
    
    FOR V_ROW IN (SELECT EMPLOYEE_ID FROM EMPLOYEES WHERE JOB_ID=P_JOB_ID) LOOP
        UPDATE EMPLOYEES
        SET
            SALARY = P_NEW_SALARY
        WHERE EMPLOYEE_ID = V_ROW.EMPLOYEE_ID;
    END LOOP;
    COMMIT;
    
    P_ID := 1;
    
EXCEPTION 
WHEN E_SALARY_OUT_OF_BOUNDS THEN
    P_ID := -1;
    IF V_BOUND_TRESPASSED THEN
        P_ERROR := 'EL SALARIO SUPERA EL MAXIMO SALARIO DEL TRABAJO INGRESADO';
    ELSE
        P_ERROR := 'EL SALARIO ES MENOR AL MINIMO SALARIO DEL TRABAJO INGRESADO';
    END IF;
WHEN OTHERS THEN
    P_ID := -1;
    P_ERROR := SQLERRM;
    
    
END PR_ACTUALIZAR_SALARIOS;
/
SELECT * FROM JOBS WHERE JOB_ID='IT_PROG';
SELECT * FROM employees WHERE JOB_ID='IT_PROG';
/
DECLARE
V_ID NUMBER;
V_ERROR VARCHAR2(200);
BEGIN
    PR_ACTUALIZAR_SALARIOS('IT_PROG', 2000, V_ID, V_ERROR);
    DBMS_OUTPUT.PUT_LINE('P_ID: ' || V_ID || ' - ' || V_ERROR);
    PR_ACTUALIZAR_SALARIOS('IT_PROG', 14000, V_ID, V_ERROR);
    DBMS_OUTPUT.PUT_LINE('P_ID: ' || V_ID || ' - ' || V_ERROR);
    PR_ACTUALIZAR_SALARIOS('IT_PROG', 8000, V_ID, V_ERROR);
    DBMS_OUTPUT.PUT_LINE('P_ID: ' || V_ID || ' - ' || V_ERROR);
END;
/
SELECT * FROM employees WHERE JOB_ID='IT_PROG';