CREATE OR REPLACE PACKAGE PCK_EMPLOYEES AS
    
    PROCEDURE PR_ALTA_EMPLOYEES
    (
        P_EMPLOYEE_ID EMPLOYEES.EMPLOYEE_ID%TYPE,
        P_FIRST_NAME EMPLOYEES.FIRST_NAME%TYPE,
        P_LAST_NAME	EMPLOYEES.LAST_NAME%TYPE,
        P_EMAIL	EMPLOYEES.EMAIL%TYPE,
        P_PHONE_NUMBER	EMPLOYEES.PHONE_NUMBER%TYPE,
        P_HIRE_DATE	EMPLOYEES.HIRE_DATE%TYPE,
        P_JOB_ID EMPLOYEES.JOB_ID%TYPE,
        P_SALARY EMPLOYEES.SALARY%TYPE,
        P_COMMISSION_PCT EMPLOYEES.COMMISSION_PCT%TYPE,
        P_MANAGER_ID EMPLOYEES.MANAGER_ID%TYPE,
        P_DEPARTMENT_ID	EMPLOYEES.DEPARTMENT_ID%TYPE,
        P_ID  OUT NUMBER, 
        P_ERROR OUT VARCHAR2
    );
    
    PROCEDURE PR_BAJA_EMPLOYEES(P_EMPLOYEE_ID IN NUMBER, P_ID OUT NUMBER, P_ERROR OUT VARCHAR2);
    
    PROCEDURE PR_MODIFICACION_EMPLOYEES(P_EMPLOYEE_ID EMPLOYEES.EMPLOYEE_ID%TYPE,
        P_FIRST_NAME EMPLOYEES.FIRST_NAME%TYPE,
        P_LAST_NAME	EMPLOYEES.LAST_NAME%TYPE,
        P_EMAIL	EMPLOYEES.EMAIL%TYPE,
        P_PHONE_NUMBER	EMPLOYEES.PHONE_NUMBER%TYPE,
        P_HIRE_DATE	EMPLOYEES.HIRE_DATE%TYPE,
        P_JOB_ID EMPLOYEES.JOB_ID%TYPE,
        P_SALARY EMPLOYEES.SALARY%TYPE,
        P_COMMISSION_PCT EMPLOYEES.COMMISSION_PCT%TYPE,
        P_MANAGER_ID EMPLOYEES.MANAGER_ID%TYPE,
        P_DEPARTMENT_ID	EMPLOYEES.DEPARTMENT_ID%TYPE,
        P_ID  OUT NUMBER, 
        P_ERROR OUT VARCHAR2);
    
    PROCEDURE PR_CONSULTA_EMPLOYEES(P_EMPLOYEE_ID	EMPLOYEES.EMPLOYEE_ID%TYPE,
        P_FIRST_NAME EMPLOYEES.FIRST_NAME%TYPE,
        P_LAST_NAME	EMPLOYEES.LAST_NAME%TYPE,
        P_EMAIL	EMPLOYEES.EMAIL%TYPE,
        P_PHONE_NUMBER	EMPLOYEES.PHONE_NUMBER%TYPE,
        P_HIRE_DATE	EMPLOYEES.HIRE_DATE%TYPE,
        P_JOB_ID EMPLOYEES.JOB_ID%TYPE,
        P_SALARY EMPLOYEES.SALARY%TYPE,
        P_COMMISSION_PCT EMPLOYEES.COMMISSION_PCT%TYPE,
        P_MANAGER_ID EMPLOYEES.MANAGER_ID%TYPE,
        P_DEPARTMENT_ID	EMPLOYEES.DEPARTMENT_ID%TYPE,
        O_CUR OUT SYS_REFCURSOR,
        P_ID  OUT NUMBER, 
        P_ERROR OUT VARCHAR2);
    
END;