CREATE OR REPLACE PROCEDURE PR_CONSULTAR_MEDICAMENTOS(P_DROGA VARCHAR2, P_NOMBRE VARCHAR2, P_MARCA VARCHAR2, O_CUR OUT SYS_REFCURSOR, P_ID OUT NUMBER, P_ERROR OUT VARCHAR2)
AS
BEGIN
    OPEN O_CUR FOR 
    SELECT COD_MEDICAMENTO, NOMBRE, MARCA, PRECIO, CANTIDAD_STOCK
    FROM MEDICAMENTOS
    WHERE
        (DROGA = P_DROGA OR P_DROGA IS NULL)
        AND
        (NOMBRE = P_NOMBRE OR P_NOMBRE IS NULL)
        AND
        (MARCA = P_MARCA OR P_MARCA IS NULL);
        P_ID := 1;
EXCEPTION
    WHEN OTHERS THEN
        P_ID := -1;
        P_ERROR := SQLERRM;

END PR_CONSULTAR_MEDICAMENTOS;