CREATE OR REPLACE TRIGGER TG_JOB_UPDATE
AFTER UPDATE ON JOBS
FOR EACH ROW
DECLARE
BEGIN
    FOR V_ROW IN (SELECT * FROM EMPLOYEES WHERE JOB_ID=:NEW.JOB_ID) LOOP
        IF (V_ROW.SALARY > :NEW.MAX_SALARY) OR (V_ROW.SALARY < :NEW.MIN_SALARY) THEN
            INSERT INTO JOBS_LOG(employee_id, salary, job_id, min_salary, max_salary) VALUES (V_ROW.EMPLOYEE_ID, V_ROW.SALARY, V_ROW.JOB_ID, :NEW.MIN_SALARY, :NEW.MAX_SALARY);
        END IF;
    END LOOP;
END;
