SET SERVEROUT ON
DECLARE
    V_AUMENTO NUMBER;
    V_AVERAGE NUMBER;
BEGIN
    SELECT AVG(E.SALARY) AS AVERAGE INTO V_AVERAGE FROM EMPLOYEES E INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;
    V_AUMENTO := V_AVERAGE*0.2;
    DBMS_OUTPUT.PUT_LINE ('EL AUMENTO SERA DE: $' || V_AUMENTO);
    
END;
