SET SERVEROUTPUT ON

DECLARE
    V_COUNTRY_NAME COUNTRIES.COUNTRY_NAME%TYPE;
    V_COUNTRY_ID COUNTRIES.COUNTRY_ID%TYPE;
    V_REGION_NAME REGIONS.REGION_NAME%TYPE;
    V_REGION_ID REGIONS.REGION_ID%TYPE;
    V_REGION_MAX_SAL EMPLOYEES.SALARY%TYPE;

BEGIN

    FOR V_ROW IN (SELECT C.COUNTRY_NAME, C.COUNTRY_ID, R.REGION_NAME, R.REGION_ID FROM COUNTRIES C INNER JOIN REGIONS R ON C.REGION_ID = R.REGION_ID) LOOP
        V_COUNTRY_NAME := V_ROW.COUNTRY_NAME;
        V_COUNTRY_ID := V_ROW.COUNTRY_ID;
        V_REGION_NAME := V_ROW.REGION_NAME;
        V_REGION_ID := V_ROW.REGION_ID;
        SELECT COALESCE(MAX(E.SALARY), 0) AS MAX INTO V_REGION_MAX_SAL FROM (((EMPLOYEES E JOIN DEPARTMENTS D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID) JOIN LOCATIONS L ON D.LOCATION_ID=L.LOCATION_ID) JOIN COUNTRIES C ON L.COUNTRY_ID=C.COUNTRY_ID) JOIN REGIONS R ON C.REGION_ID=R.REGION_ID  WHERE R.REGION_ID=V_REGION_ID;
        DBMS_OUTPUT.PUT_LINE ('' || V_COUNTRY_NAME || '(' || V_COUNTRY_ID || ')' || V_REGION_NAME || '(SALARIO_MAX: ' || V_REGION_MAX_SAL || ')');
    END LOOP;

END;

