SET SERVEROUTPUT ON

DECLARE
    V_COUNTRY_NAME countries.country_name%TYPE;

BEGIN
    V_COUNTRY_NAME := '';
    FOR V_ROW IN (SELECT COUNTRY_NAME FROM COUNTRIES C INNER JOIN REGIONS R ON R.REGION_ID = C.REGION_ID WHERE C.REGION_ID = 2 ) LOOP
    
        V_COUNTRY_NAME := V_ROW.COUNTRY_NAME;
        DBMS_OUTPUT.PUT_LINE ('PAÍS: [' || V_COUNTRY_NAME || ']' );
    END LOOP;

END;