DECLARE 
    CURSOR CUR_EMP IS
        (SELECT EMPLOYEE_ID, SALARY
        FROM EMPLOYEES
        ORDER BY SALARY DESC
        FETCH FIRST 10 ROWS ONLY);
    V_DDL VARCHAR2(100);
        
BEGIN
    OPEN CUR_EMP;
    V_DDL := 'CREATE TABLE TOP_SALARY(EMPLOYEE_ID NUMBER(10) PRIMARY KEY, SALARY NUMBER(8,2) NOT NULL)';
    EXECUTE IMMEDIATE V_DDL;
    INSERT INTO TOP_SALARY VALUES CUR_EMP;
    
END;

--NO FUNCIONA, BUSQUE EN VARIAS FUENTES Y NINGUNA ME BRINDO UNA SOLUCIÓN AL PROBLEMA