SET SERVEROUTPUT ON
DECLARE
    V_FIRST_NAME EMPLOYEES.FIRST_NAME%TYPE;
    V_LAST_NAME EMPLOYEES.LAST_NAME%TYPE;
    
BEGIN
    SELECT FIRST_NAME, LAST_NAME
    INTO V_FIRST_NAME, V_LAST_NAME
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = 100;
    
    DBMS_OUTPUT.PUT_LINE ('NOMBRE: ' || V_FIRST_NAME || ', ' || 'APELLIDO: ' || V_LAST_NAME);

END;