CREATE OR REPLACE FUNCTION FC_OBT_JOBS (P_SALARY EMPLOYEES.SALARY%TYPE) RETURN SYS_REFCURSOR
AS
CUR_EMP SYS_REFCURSOR;
BEGIN
    OPEN CUR_EMP FOR SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.LAST_NAME, E.SALARY, J.JOB_TITLE, J.MIN_SALARY, J.MAX_SALARY FROM EMPLOYEES E JOIN JOBS J ON E.JOB_ID=J.JOB_ID WHERE P_SALARY>MIN_SALARY AND P_SALARY<MAX_SALARY;
    RETURN CUR_EMP;
END;
/
--TEST
DECLARE
CUR_EMP SYS_REFCURSOR;
BEGIN
CUR_EMP := HR.FC_OBT_JOBS(6400);
DBMS_SQL.return_result(CUR_EMP);
END;