CREATE OR REPLACE FUNCTION FD_DIFERENCIA_SALARIO (P_EMPLOYEE_ID NUMBER, P_MAX_MIN BOOLEAN DEFAULT FALSE) RETURN NUMBER
AS

V_SALARY EMPLOYEES.SALARY%TYPE;
V_JOB_ID EMPLOYEES.JOB_ID%TYPE;
V_MIN_SALARY EMPLOYEES.SALARY%TYPE;
V_MAX_SALARY EMPLOYEES.SALARY%TYPE;
V_SALARY_DIFF EMPLOYEES.SALARY%TYPE;

BEGIN
    SELECT E.SALARY, J.JOB_ID, J.MIN_SALARY, J.MAX_SALARY INTO V_SALARY, V_JOB_ID, V_MIN_SALARY, V_MAX_SALARY FROM EMPLOYEES E JOIN JOBS J ON E.JOB_ID=J.JOB_ID WHERE EMPLOYEE_ID=P_EMPLOYEE_ID;
    IF P_MAX_MIN THEN
        V_SALARY_DIFF := V_MAX_SALARY - V_SALARY;
    ELSE
        V_SALARY_DIFF :=  V_SALARY - V_MIN_SALARY;
    END IF;
    RETURN V_SALARY_DIFF;
END;
/
SET SERVEROUTPUT ON
DECLARE
    V_EMPLOYEE_ID EMPLOYEES.EMPLOYEE_ID%TYPE;
    V_FIRST_NAME EMPLOYEES.FIRST_NAME%TYPE;
    V_LAST_NAME EMPLOYEES.LAST_NAME%TYPE;
    V_NAME EMPLOYEES.FIRST_NAME%TYPE;
    V_SALARY EMPLOYEES.SALARY%TYPE;
    V_MAX_SALARY EMPLOYEES.SALARY%TYPE;
    V_MIN_SALARY EMPLOYEES.SALARY%TYPE;
BEGIN
    V_EMPLOYEE_ID := 166;
    V_MAX_SALARY := FD_DIFERENCIA_SALARIO(V_EMPLOYEE_ID, TRUE);
    V_MIN_SALARY := FD_DIFERENCIA_SALARIO(V_EMPLOYEE_ID);
    SELECT FIRST_NAME, LAST_NAME, SALARY INTO V_FIRST_NAME, V_LAST_NAME, V_SALARY FROM EMPLOYEES WHERE EMPLOYEE_ID=V_EMPLOYEE_ID;
    V_NAME := V_LAST_NAME || ', ' || V_FIRST_NAME;
    DBMS_OUTPUT.PUT_LINE(V_NAME || ' - ' || V_SALARY || '( '||V_MIN_SALARY ||' - ' || V_MAX_SALARY ||' )');
END;