CREATE OR REPLACE FUNCTION FC_OBT_EMPLOYEES (P_DEPARTMENT_ID DEPARTMENTS.DEPARTMENT_ID%TYPE) RETURN SYS_REFCURSOR 
AS
CUR_EMP SYS_REFCURSOR;
BEGIN
    OPEN CUR_EMP FOR SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.LAST_NAME FROM EMPLOYEES E INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID WHERE E.DEPARTMENT_ID=P_DEPARTMENT_ID;
    RETURN CUR_EMP;
END;
/
DECLARE
CUR_EMP_SIETE SYS_REFCURSOR;
CUR_EMP_DIEZ SYS_REFCURSOR;
BEGIN
CUR_EMP_SIETE := HR.FC_OBT_EMPLOYEES(7);
CUR_EMP_DIEZ := HR.FC_OBT_EMPLOYEES(10);
DBMS_SQL.return_result(CUR_EMP_SIETE);
DBMS_SQL.return_result(CUR_EMP_DIEZ);
END;